name: einvoice-provider

networks:
  einvoice-nw:
    driver: bridge
    name: einvoice-nw

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./docker/docker_data/mongodb_data:/data/db
    networks:
      - einvoice-nw
  postgres:
    image: postgres
    container_name: postgres_server
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: einvoice-app
      PGDATA: /var/lib/postgresql/custom_data
    ports:
      - '5432:5432'
    volumes:
      - ./docker/docker_data/postgres_data:/var/lib/postgresql/custom_data
    networks:
      - einvoice-nw
  pgadmin:
    container_name: pgadmin_ui
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '5050:80'
    volumes:
      - ./docker/docker_data/pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - einvoice-nw
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: keycloak-25.0.0
    ports:
      - '8180:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    command: start-dev
    restart: unless-stopped
    volumes:
      - ./docker/docker_data/keycloak_data:/opt/keycloak/data
    networks:
      - einvoice-nw
  redis:
    image: redis
    container_name: redis_server
    ports:
      - '6379:6379'
    networks:
      - einvoice-nw
    restart: unless-stopped
    volumes:
      - ./docker/docker_data/redis_data:/data
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight-ui
    ports:
      - '5540:5540'
    networks:
      - einvoice-nw
    depends_on:
      - redis
    volumes:
      - ./docker/docker_data/redisinsight_data:/data
  kafka:
    container_name: kafka_server
    image: bitnamilegacy/kafka
    networks:
      - einvoice-nw
    ports:
      - 9092:9092 # internal Docker network listener (optionally)
      - 29092:29092 # external listener, host local connect
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@localhost:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - ./docker/docker_data/kafka_data/bitnami_data:/bitnami/kafka
    restart: unless-stopped
