name: einvoice-provider

networks:
  einvoice-nw:
    driver: bridge
    name: einvoice-nw

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./docker/docker_data/mongodb_data:/data/db
    networks:
      - einvoice-nw
  postgres:
    image: postgres
    container_name: postgres_server
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: einvoice-app
      PGDATA: /var/lib/postgresql/custom_data
    ports:
      - '5432:5432'
    volumes:
      - ./docker/docker_data/postgres_data:/var/lib/postgresql/custom_data
    networks:
      - einvoice-nw
  pgadmin:
    container_name: pgadmin_ui
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '5050:80'
    volumes:
      - ./docker/docker_data/pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - einvoice-nw
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: keycloak-25.0.0
    ports:
      - '8180:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    command: start-dev
    restart: unless-stopped
    volumes:
      - ./docker/docker_data/keycloak_data:/opt/keycloak/data
    networks:
      - einvoice-nw
