export enum ERROR_CODE {
  PRODUCT_ALREADY_EXISTS = 'PRODUCT_ALREADY_EXISTS',

  INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND',
  INVOICE_CAN_NOT_BE_DELETED = 'INVOICE_CAN_NOT_BE_DELETED',
  INVOICE_CAN_NOT_BE_UPDATED = 'INVOICE_CAN_NOT_BE_UPDATED',
  INVOICE_CAN_NOT_BE_SENT = 'INVOICE_CAN_NOT_BE_SENT',

  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  PERMISSION_DENIED = 'PERMISSION_DENIED',
}
