export enum TcpServices {
  PRODUCT = 'TCP_PRODUCT',
  INVOICE = 'TCP_INVOICE',
  USER_ACCESS = 'TCP_USER_ACCESS',
  AUTHORIZER = 'TCP_AUTHORIZER',
  PDF_GENERATOR = 'TCP_PDF_GENERATOR',
  MEDIA = 'TCP_MEDIA',
  PAYMENT = 'TCP_PAYMENT',
}
