syntax = "proto3";

package GRPC_USER_ACCESS_SERVICE;

service UserService {
  rpc getUserInfo (GetUserInfoRequest) returns (GetUserInfoResponse);
}

message GetUserInfoRequest {
  string token = 1;
}

message GetUserInfoResponse {
  string code = 1;
  User data = 2;
  string error = 3;
}

message Role {
  string name = 1;
  string description = 2;
  repeated string permissions = 3;
}

message User {
  string _id = 1;
  string id = 2;
  string firstName = 3;
  string lastName = 4;
  string email = 5;
  repeated Role roles = 6;
}
